---
- name: Configure SSH
  hosts: all
  tasks:
    - name: Check SSH connection
      ansible.builtin.command: hostname
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400