---
- name: Configure SSH
  hosts: all
  tasks:
    - name: Add hosts to known_hosts
      shell: "ssh-keyscan -H {{ hostvars[item].ansible_host }} >> ~/.ssh/known_hosts"
      delegate_to: localhost
      run_once: yes
      loop: "{{ groups['proxy'] + groups['gateway'] }}"
    - name: Check SSH connection
      command: hostname
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install nginx
      become: yes
      apt:
        pkg: "nginx"
        state: "present"