---
- name: Configure gateway
  hosts: gateway
  tasks:
    - name: Install docker
      apt:
        pkg: "docker.io"
        state: "present"
    - name: Create a duckdns container
      become: yes
      community.docker.docker_container:
        name: duckdns
        image: lscr.io/linuxserver/duckdns:latest
        restart_policy: "unless-stopped"
        env:
          UPDATE_IP: "true"
          SUBDOMAINS: "{{ gateway_subdomain }}"
          TOKEN: "{{ token }}"