---
- name: Configure gateway
  hosts: gateway
  tasks:
    - name: Install docker
      become: true
      shell: "apt install docker.io -y"
    - name: Create a duckdns container
      become: true
      community.docker.docker_container:
        name: duckdns
        image: lscr.io/linuxserver/duckdns:latest
        restart_policy: "unless-stopped"
        env:
          UPDATE_IP: "true"
          SUBDOMAINS: "{{ duckdns_domain }}"
          TOKEN: "{{ duckdns_token }}"