---
- name: Configure SSH
  hosts: all
  gather_facts: no
  tasks:
    # - name: Remove conflicting IPs from known_hosts
    #   shell: "ssh-keygen -R {{ hostvars[item].ansible_host }}"
    #   delegate_to: localhost
    #   run_once: yes
    #   ignore_errors: yes
    #   loop: "{{ groups['proxy'] + groups['gateway'] }}"
    # - name: Add hosts to known_hosts
    #   shell: "ssh-keyscan -H {{ hostvars[item].ansible_host }} >> ~/.ssh/known_hosts"
    #   delegate_to: localhost
    #   run_once: yes
    #   loop: "{{ groups['proxy'] + groups['gateway'] }}"
    # - name: Wait for system to become reachable
    #   ansible.builtin.wait_for_connection:
    #     timeout: 900
    # - name: Gather facts for first time
    #   ansible.builtin.setup:
    # - name: Check SSH connection
    #   command: hostname
    - name: Install Wireguard
      become: yes
      ansible.builtin.package:
        name: wireguard-tools
        state: present
      register: result
      until: result is success
      retries: 5
      delay: 10

- hosts: proxy
  become: yes
  tasks:
    - name: Generate Wireguard keys on proxy
      shell: "wg genkey | tee privatekey_proxy | wg pubkey > publickey_proxy"
      args:
        chdir: "/etc/wireguard"
    - name: Get public key of proxy
      slurp:
        src: /etc/wireguard/publickey_proxy
      register: public_key_proxy
    - name: Get private key of proxy
      slurp:
        src: /etc/wireguard/privatekey_proxy
      register: private_key_proxy

- hosts: gateway
  become: yes
  tasks:
    - name: Get internet-facing interface from gateway
      shell: "ip route get 8.8.8.8 | awk '/dev/ { print $5 }'"
      register: gateway_internet_interface
    - name: Generate Wireguard keys
      shell: "wg genkey | tee privatekey_gateway | wg pubkey > publickey_gateway"
      args:
        chdir: "/etc/wireguard"
    - name: Get public key of gateway
      slurp:
        src: /etc/wireguard/publickey_gateway
      register: public_key_gateway
    - name: Get private key of gateway
      slurp:
        src: /etc/wireguard/privatekey_gateway
      register: private_key_gateway

- hosts: proxy
  become: yes
  tasks:
    - name: Remove any older connection
      shell: "wg-quick down wg0 && sleep 5"
      ignore_errors: yes
    - name: Generate proxy wg0.conf file
      template:
        src: "../templates/wireguard/wg0_proxy.conf.template"
        dest: "/etc/wireguard/wg0.conf"
      vars:
        public_key: "{{ hostvars.gateway.public_key_gateway['content'] | b64decode }}"
        private_key: "{{ private_key_proxy['content'] | b64decode }}"
    - name: Startup connection
      shell: "wg-quick up wg0"
    - name: Enable wg service
      shell: "systemctl enable wg-quick@wg0"

- hosts: gateway
  become: yes
  tasks:
    - name: Remove any older connection
      shell: "wg-quick down wg0 && sleep 5"
      ignore_errors: yes
    - name: Generate gateway wg0.conf file
      template:
        src: "../templates/wireguard/wg0_gateway.conf.template"
        dest: "/etc/wireguard/wg0.conf"
      vars:
        public_key: "{{ hostvars.proxy.public_key_proxy['content'] | b64decode }}"
        private_key: "{{ private_key_gateway['content'] | b64decode }}"
        interface: "{{ gateway_internet_interface.stdout }}"
    - name: Startup connection
      shell: "wg-quick up wg0"
    - name: Enable wg service
      shell: "systemctl enable wg-quick@wg0"
