---
- hosts: proxy
  tasks:
    - name: Capture all the worker IPs
      ansible.builtin.shell: kubectl get nodes -l node-role.kubernetes.io/master!=true,node-role.kubernetes.io/controlplane!=true -o=jsonpath='{.items[*].status.addresses[?(@.type=="InternalIP")].address}' |  tr " " "\n"
      register: nodes
      delegate_to: localhost
    - name: Setup nginx config
      become: yes
      template:
        src: "../templates/nginx/proxy.template"
        dest: "/etc/nginx/sites-available/default"
    - name: Restart nginx
      become: yes
      ansible.builtin.shell: systemctl restart nginx

- hosts: gateway
  become: yes
  tasks:
    - name: Setup nginx config
      template:
        src: "../templates/nginx/gateway.template"
        dest: "/etc/nginx/sites-available/default"
    - name: Restart nginx
      ansible.builtin.shell: systemctl restart nginx