---
- hosts: proxy
  tasks:
    - name: Install nginx
      become: true
      apt:
        pkg: "nginx"
        state: "present"
    - name: Capture all the worker IPs
      ansible.builtin.shell: kubectl get nodes -l node-role.kubernetes.io/master!=true,node-role.kubernetes.io/controlplane!=true -o=jsonpath='{.items[*].status.addresses[?(@.type=="InternalIP")].address}' |  tr " " "\n"
      register: nodes
      delegate_to: localhost
    - name: Setup nginx config
      become: true
      template:
        src: "../templates/nginx-backend.template"
        dest: "/etc/nginx/sites-available/default"
    - name: Restart nginx
      become: true
      ansible.builtin.shell: systemctl restart nginx

- hosts: gateway
  tasks:
    - name: Create a dir for caddy configs
      shell: "mkdir -p ~/caddy"
    - name: Setup caddy config
      template:
        src: "../templates/caddyfile.template"
        dest: "~/caddy/Caddyfile"
    - name: Create a caddy container
      become: true
      community.docker.docker_container:
        name: caddy
        image: docker.io/caddy:alpine
        restart_policy: "unless-stopped"
        published_ports:
          - 80:80
          - 443:443
        volumes:
          - ./caddy/data/:/data/
          - ./caddy/config/:/config/
          - ./caddy/Caddyfile:/etc/caddy/Caddyfile