apiVersion: v1
data:
  endpoint_domain: example.duckdns.org
  interface_name: enp0s3
  load_balancer_ip: 119.155.46.210
  load_balancer_user: ubuntu
kind: ConfigMap
metadata:
  name: my-config
  # namespace: default