apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wireguard-lb
  # namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: wireguard-lb
  template:
    metadata:
      name: wireguard-lb
      labels:
        k8s-app: wireguard-lb
    spec:
      serviceAccountName: wireguard-lb-sa
      initContainers:
        - name: wait-for-wireguard-init
          image: bitnami/kubectl:latest
          command: ["kubectl"]
          args: ["wait", "--for=condition=Complete", "job/wireguard-init"]
        - name: init-container
          image: linuxserver/wireguard:latest
          command: ["/bin/sh", "-c"]
          args:
            - CLIENT_PRIVATE_KEY=$(wg genkey);
              CLIENT_PUBLIC_KEY=$(echo "$CLIENT_PRIVATE_KEY" | wg pubkey);
              echo "$CLIENT_PRIVATE_KEY" > /config/CLIENT_PRIVATE_KEY;
              echo "$CLIENT_PUBLIC_KEY" > /config/CLIENT_PUBLIC_KEY;
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: wireguard-lb
          image: namanarora/wireguard-lb:latest
          volumeMounts:
            - name: secret-volume
              mountPath: /workspace/ssh
              subPath: ssh-key
            - name: config
              mountPath: /workspace/config
          envFrom:
            - configMapRef:
                name: my-config
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          livenessProbe:
            exec:
              command:
              - ping 
              - -c 
              - "1"
              - -W
              - "2"
              - "10.1.0.1"
            initialDelaySeconds: 15
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/rbash", "remove_peer.sh"]
      volumes:
        - name: secret-volume
          secret:
            secretName: ssh-key-secret
            items:
              - key: ssh-key
                path: ssh-key
                mode: 0600 
        - name: modules-volume
          hostPath:
            path: /lib/modules
        - name: config
          emptyDir: {}
      securityContext:
        runAsUser: 1000
        runAsGroup: 0
        fsGroup: 1000
      restartPolicy: Always