apiVersion: batch/v1
kind: Job
metadata:
  name: wireguard-init
  #namespace: default
spec:
  template:
    spec:
      containers:
        - name: wireguard-init-container
          image: namanarora/wireguard-lb:latest
          command: ["/bin/sh"]
          args: ["init.sh"]
          volumeMounts:
            - name: secret-volume
              mountPath: /ssh
              subPath: ssh-key
          envFrom:
            - configMapRef:
                name: my-config
          # env:
          #   - name: PUID
          #     value: "1000"
          #   - name: PGID
          #     value: "1000"
          #   - name: TZ
          #     value: "Asia/Kolkata"
      volumes:
        - name: secret-volume
          secret:
            secretName: ssh-key-secret
            items:
              - key: ssh-key
                path: ssh-key
                mode: 0600
      restartPolicy: OnFailure