apiVersion: v1
kind: Pod
metadata:
  name: wireguard-pod
spec:
  containers:
    - name: wireguard
      image: namanarora/wireguard-lb:latest
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: secret-volume
          mountPath: /ssh
          subPath: ssh-key
      envFrom:
        - configMapRef:
            name: my-config
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Kolkata"
  volumes:
    - name: secret-volume
      secret:
        secretName: ssh-key-secret
        items:
          - key: ssh-key
            path: ssh-key
            mode: 0600 
    - name: modules-volume
      hostPath:
        path: /lib/modules
  restartPolicy: Always